######################################################
# Encodings-profiles for Audio only                  #
######################################################

profile.audio-to-mp3.http.name = audio-to-mp3
profile.audio-to-mp3.http.input = audio
profile.audio-to-mp3.http.output = audio
profile.audio-to-mp3.http.suffix = -audio.mp3
profile.audio-to-mp3.http.mimetype = audio/mpeg
profile.audio-to-mp3.http.ffmpeg.command = -i #{in.video.path} -vn -map_metadata -1 -sn -acodec libmp3lame -ab 128k -ar 44100 -ac 2  #{out.dir}/#{out.name}#{out.suffix}

profile.audio-to-m4a.http.name = audio-to-m4a
profile.audio-to-m4a.http.input = audio
profile.audio-to-m4a.http.output = audio
profile.audio-to-m4a.http.suffix = -audio.m4a
profile.audio-to-m4a.http.mimetype = audio/mp4
profile.audio-to-m4a.http.ffmpeg.command = -i #{in.video.path} -vn -map_metadata -1 -sn -acodec aac -ab 96k -ar 44100 -ac 2 #{out.dir}/#{out.name}#{out.suffix}

profile.audio-to-ogg.http.name = audio-to-ogg
profile.audio-to-ogg.http.input = audio
profile.audio-to-ogg.http.output = audio
profile.audio-to-ogg.http.suffix = -audio.ogg
profile.audio-to-ogg.http.mimetype = audio/ogg
profile.audio-to-ogg.http.ffmpeg.command = -i #{in.video.path} -vn -map_metadata -1 -sn -acodec libvorbis -ab 96k -ar 44100 -ac 2  #{out.dir}/#{out.name}#{out.suffix}

profile.audio-only-to-opus.transcription.name = extract audio stream for transcription
profile.audio-only-to-opus.transcription.input = visual
profile.audio-only-to-opus.transcription.output = audio
profile.audio-only-to-opus.transcription.jobload = 0.5
profile.audio-only-to-opus.transcription.suffix = .ogg
profile.audio-only-to-opus.transcription.mimetype = audio/ogg
profile.audio-only-to-opus.transcription.ffmpeg.command = -i #{in.video.path} \
    -vn -dn -sn -map_metadata -1 \
    -c:a libopus -b:a 24k -ac 1 -ar 16k \
    #{out.dir}/#{out.name}#{out.suffix}
